services:
  - type: web
    name: daftech-crm
    runtime: node
    plan: free
    rootDir: ng/daftech-crm
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0